name: Maven CI

on:
  push:
    branches:
      - main  # Change 'main' to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Use the Java version you need

      - name: Build with Maven
        run: mvn clean install
